properties:
    iteration_limit: 1000
    return_first: true
    time_limit: 30 # smaller limit, more molecules?
    max_transforms: 6

policy:
  files:
    full_uspto:
      - data/full_uspto_03_05_19_rollout_policy.hdf5
      - data/full_uspto_03_05_19_unique_templates.hdf5
stock:
  files:
    zinc: data/zinc_stock_17_04_20.hdf5